branches:
  only:
  - v3.0
# os: osx

language: node_js
node_js:
  - "8"
dist: trusty
services:
  - postgresql
  - docker
before_install:
   - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
   - npm install -g protractor
   - webdriver-manager update

addons:
  chrome: stable

before_script:
   - psql -c "ALTER USER postgres WITH PASSWORD 'zenvisage';" -U postgres 
   - psql -c "ALTER USER postgres WITH SUPERUSER;" -U postgres
   - psql -c "ALTER DATABASE postgres OWNER TO travis;"
   - psql -c "DROP schema public cascade;" -U postgres
   - psql -c "CREATE schema public;" -U postgres 
   - psql -c "CREATE TABLE zenvisage_metafilelocation (database TEXT, metafilelocation TEXT, csvfilelocation TEXT);" -U postgres
   - psql -c "CREATE TABLE zenvisage_metatable (tablename TEXT, attribute TEXT, type TEXT, axis TEXT, min FLOAT, max FLOAT, selectedX BOOLEAN, selectedY BOOLEAN, selectedZ BOOLEAN);" -U postgres
   - psql -c "CREATE TABLE zenvisage_dynamic_classes (tablename TEXT, attribute TEXT, ranges TEXT);" -U postgres
   - psql -c "CREATE TABLE dynamic_class_aggregations (Table_Name TEXT NOT NULL, Tag TEXT NOT NULL, Attributes TEXT NOT NULL, Ranges TEXT NOT NULL, Count INT NOT NULL);" -U postgres
   - psql -c "CREATE TABLE users (id TEXT, password TEXT);" -U postgres
   - psql -c "CREATE TABLE users_tables (users TEXT, tables TEXT);" -U postgres
   - psql -c "INSERT INTO users_tables (users, tables) VALUES ('public', 'cmu'), ('public', 'flights'),('public', 'real_estate'),('public', 'weather'),('public', 'real_estate_tutorial');" -U postgres
   - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;" -U postgres
   - psql -l
   - psql -c "\du"
   - psql -c "\dt" -U postgres
   - bash travis_build.sh
   - ls -ld /home/travis
   - ls -ld /home/travis/build
   - ls -ld /home/travis/build/zenvisage
   - ls -ld /home/travis/build/zenvisage/zenvisage
   - ls -ld /home/travis/build/zenvisage/zenvisage/target
   - chmod a+rX /home/travis /home/travis/build /home/travis/build/zenvisage /home/travis/build/zenvisage/zenvisage /home/travis/build/zenvisage/zenvisage/target /home/travis/build/zenvisage/zenvisage/target/classes /home/travis/build/zenvisage/zenvisage/target/classes/data /home/travis/build/zenvisage/zenvisage/target/classes/data/real_estate.csv
script: bash travis_shell.sh
  #bash travis_docker.sh

